import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, BarChart3, ChevronDown, ChevronRight, Loader2, RefreshCw, Users } from 'lucide-react';
import projectApi from '@/api/project';
import { useAuth } from '@/contexts/AuthContext';
import './DevelopmentProgressPage.css';

const STATUS_ORDER = ['open', 'in_progress', 'pending_review', 'done', 'blocked', 'dismissed'];
const STATUS_LABELS = {
    open: '未开始',
    in_progress: '进行中',
    pending_review: '上报完成',
    done: '已完成',
    blocked: '阻塞',
    dismissed: '已忽略',
};

const DEV_TYPE_LABELS = {
    dev_backend: '后端',
    dev_frontend: '前端',
    dev_ui: 'UI',
    dev_product: '产品',
};
const TYPE_ORDER = ['dev_frontend', 'dev_backend', 'dev_ui', 'dev_product', 'other'];
const TYPE_LABELS = {
    dev_frontend: '前端',
    dev_backend: '后端',
    dev_ui: 'UI',
    dev_product: '产品',
    other: '其他',
};
const PRIORITY_OPTIONS = ['p0', 'p1', 'p2', 'p3'];
const STATUS_PROGRESS = {
    open: 10,
    in_progress: 55,
    pending_review: 90,
    done: 100,
    blocked: 40,
    dismissed: 100,
};

function getDevTypes(row) {
    if (!row) return [];
    return ['dev_backend', 'dev_frontend', 'dev_ui', 'dev_product'].filter((k) => {
        const v = String(row[k] || '').trim();
        return v && v !== '-' && v !== '0';
    });
}

function buildTaskTitle(row, devType) {
    const typeLabel = DEV_TYPE_LABELS[devType] || devType;
    const name = [row.l1_feature, row.l2_feature].filter(Boolean).join(' - ');
    return `[${typeLabel}] ${name || '开发任务'}`;
}

function getTaskTypeKey(task) {
    const tag = task?.tags?.[0];
    return TYPE_LABELS[tag] ? tag : 'other';
}

export default function DevelopmentProgressPage() {
    const { id } = useParams();
    const navigate = useNavigate();
    const { user } = useAuth();

    const [project, setProject] = useState(null);
    const [tasks, setTasks] = useState([]);
    const [members, setMembers] = useState([]);
    const [loading, setLoading] = useState(true);
    const [generating, setGenerating] = useState(false);
    const [assigningTaskId, setAssigningTaskId] = useState(null);
    const [error, setError] = useState(null);
    const [opMessage, setOpMessage] = useState(null);
    const [viewMode, setViewMode] = useState('table');
    const [collapsedTypeMap, setCollapsedTypeMap] = useState({});
    const autoGeneratedRef = useRef(false);

    const autoGenerateTasks = useCallback(async (proj, candidateMembers, featureList) => {
        setGenerating(true);
        try {
            const fallbackAssignee = proj?.pm_user_id || candidateMembers[0]?.id || user?.id;
            const dueAtIso = proj?.due_at ? `${proj.due_at}T18:00:00` : null;
            const generated = [];
            featureList.forEach((row, index) => {
                const types = getDevTypes(row);
                types.forEach((devType) => {
                    generated.push({
                        title: buildTaskTitle(row, devType),
                        description: row.description || '',
                        assignee_user_id: fallbackAssignee,
                        priority: 'p2',
                        due_at: dueAtIso,
                        dev_type: devType,
                        feature_key: `${index}|${devType}`,
                    });
                });
            });
            if (generated.length > 0) {
                await projectApi.generateDevTasks(id, generated);
                const todoRes = await projectApi.getProjectTodos(id);
                setTasks(todoRes.data || []);
            }
        } catch (err) {
            setError(err?.response?.data?.message || err?.message || '自动生成开发任务失败');
        } finally {
            setGenerating(false);
        }
    }, [id, user?.id]);

    const load = useCallback(async () => {
        setLoading(true);
        setError(null);
        try {
            const [projectRes, todoRes, featureRes] = await Promise.all([
                projectApi.getProject(id),
                projectApi.getProjectTodos(id),
                projectApi.getProjectFeatureList(id),
            ]);

            const proj = projectRes.data;
            const todoItems = todoRes.data || [];
            const featureData = featureRes.data || {};
            const featureMembers = featureData.members || [];
            const pm = proj?.pm_user_id
                ? { id: proj.pm_user_id, display_name: proj.pm_name || '项目经理', is_pm: true }
                : null;
            const mergedMembers = pm
                ? [pm, ...featureMembers.filter((m) => m.id !== pm.id)]
                : featureMembers;

            setProject(proj);
            setTasks(todoItems);
            setMembers(mergedMembers);

            if (!autoGeneratedRef.current && todoItems.length === 0 && (featureData.feature_list || []).length > 0) {
                autoGeneratedRef.current = true;
                await autoGenerateTasks(proj, mergedMembers, featureData.feature_list);
            }
        } catch (err) {
            setError(err?.response?.data?.message || err?.message || '加载开发进度失败');
        } finally {
            setLoading(false);
        }
    }, [autoGenerateTasks, id]);

    useEffect(() => {
        if (id) load();
    }, [id, load]);

    const stats = useMemo(() => {
        const total = tasks.length;
        const done = tasks.filter((t) => t.status === 'done').length;
        const inProgress = tasks.filter((t) => t.status === 'in_progress').length;
        const pendingReview = tasks.filter((t) => t.status === 'pending_review').length;
        const progress = total ? Math.round((done / total) * 100) : 0;
        return { total, done, inProgress, pendingReview, progress };
    }, [tasks]);

    const groupedByType = useMemo(() => {
        const statusRank = STATUS_ORDER.reduce((acc, cur, idx) => ({ ...acc, [cur]: idx }), {});
        const groupMap = TYPE_ORDER.reduce((acc, key) => ({ ...acc, [key]: [] }), {});
        tasks.forEach((task) => {
            const typeKey = getTaskTypeKey(task);
            groupMap[typeKey].push(task);
        });
        return TYPE_ORDER.map((typeKey) => ({
            typeKey,
            label: TYPE_LABELS[typeKey],
            items: groupMap[typeKey].sort((a, b) => {
                const sa = statusRank[a.status] ?? 999;
                const sb = statusRank[b.status] ?? 999;
                if (sa !== sb) return sa - sb;
                if (!a.due_at && !b.due_at) return 0;
                if (!a.due_at) return 1;
                if (!b.due_at) return -1;
                return new Date(a.due_at).getTime() - new Date(b.due_at).getTime();
            }),
        })).filter((g) => g.items.length > 0);
    }, [tasks]);

    const orderedTasks = useMemo(() => groupedByType.flatMap((g) => g.items), [groupedByType]);

    const timeline = useMemo(() => {
        const DAY = 24 * 60 * 60 * 1000;
        const dueDates = orderedTasks
            .map((t) => (t.due_at ? new Date(t.due_at) : null))
            .filter(Boolean);
        let start = project?.start_at ? new Date(project.start_at) : null;
        if (!start && dueDates.length > 0) {
            start = new Date(Math.min(...dueDates.map((d) => d.getTime())));
        }
        if (!start) start = new Date();
        let end = dueDates.length > 0 ? new Date(Math.max(...dueDates.map((d) => d.getTime()))) : new Date(start);
        if (end.getTime() <= start.getTime()) {
            end = new Date(start.getTime() + 14 * DAY);
        }
        const totalDays = Math.max(1, Math.ceil((end.getTime() - start.getTime()) / DAY));
        return { start, end, totalDays, DAY };
    }, [orderedTasks, project?.start_at]);

    const reviewerName = project?.pm_name || '项目经理';

    const handleAssign = async (todoId, assigneeUserId) => {
        if (!assigneeUserId) return;
        try {
            setOpMessage(null);
            setAssigningTaskId(todoId);
            await projectApi.updateProjectTodoPlan(id, todoId, { assignee_user_id: assigneeUserId });
            const todoRes = await projectApi.getProjectTodos(id);
            setTasks(todoRes.data || []);
        } catch (err) {
            setOpMessage(err?.response?.data?.message || err?.message || '分配任务失败');
        } finally {
            setAssigningTaskId(null);
        }
    };

    const handleDueDate = async (todoId, dateValue) => {
        try {
            setOpMessage(null);
            setAssigningTaskId(todoId);
            const dueAt = dateValue ? `${dateValue}T18:00:00` : null;
            await projectApi.updateProjectTodoPlan(id, todoId, { due_at: dueAt });
            const todoRes = await projectApi.getProjectTodos(id);
            setTasks(todoRes.data || []);
        } catch (err) {
            setOpMessage(err?.response?.data?.message || err?.message || '修改截止日期失败');
        } finally {
            setAssigningTaskId(null);
        }
    };

    const handlePriority = async (todoId, priority) => {
        try {
            setOpMessage(null);
            setAssigningTaskId(todoId);
            await projectApi.updateProjectTodoPlan(id, todoId, { priority });
            const todoRes = await projectApi.getProjectTodos(id);
            setTasks(todoRes.data || []);
        } catch (err) {
            setOpMessage(err?.response?.data?.message || err?.message || '修改优先级失败');
        } finally {
            setAssigningTaskId(null);
        }
    };

    const toggleTypeGroup = (typeKey) => {
        setCollapsedTypeMap((prev) => ({ ...prev, [typeKey]: !prev[typeKey] }));
    };

    if (loading) {
        return (
            <div className="page-content">
                <div className="dev-progress-loading"><Loader2 size={20} className="spin" /> 加载中...</div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="page-content">
                <div className="dev-progress-error">{error}</div>
            </div>
        );
    }

    return (
        <div className="page-content dev-progress-page">
            <div className="dev-progress-toolbar">
                <button className="dev-progress-back" onClick={() => navigate(`/project/${id}`)}>
                    <ArrowLeft size={15} /> 返回项目
                </button>
                <button className="dev-progress-refresh" onClick={load}>
                    <RefreshCw size={14} /> 刷新
                </button>
            </div>

            <div className="dev-progress-hero">
                <div>
                    <p className="dev-progress-kicker">Development Progress</p>
                    <h1>{project?.name}</h1>
                    <p className="dev-progress-subtitle">
                        审核员统一为：<strong>{reviewerName}</strong>
                    </p>
                </div>
                <div className="dev-progress-meter">
                    <div className="dev-progress-percent">{stats.progress}%</div>
                    <div className="dev-progress-track">
                        <div className="dev-progress-fill" style={{ width: `${stats.progress}%` }} />
                    </div>
                    <div className="dev-progress-caption">{stats.done}/{stats.total} 已完成</div>
                </div>
            </div>

            {generating && (
                <div className="dev-progress-banner">
                    <Loader2 size={16} className="spin" /> 正在根据功能清单自动生成开发任务...
                </div>
            )}
            {opMessage && (
                <div className="dev-progress-banner" style={{ borderColor: '#fecaca', background: '#fef2f2', color: '#991b1b' }}>
                    {opMessage}
                </div>
            )}

            <div className="dev-progress-stats">
                <div className="dev-stat-card">
                    <BarChart3 size={16} />
                    <div>
                        <span>总任务</span>
                        <strong>{stats.total}</strong>
                    </div>
                </div>
                <div className="dev-stat-card">
                    <Users size={16} />
                    <div>
                        <span>进行中</span>
                        <strong>{stats.inProgress}</strong>
                    </div>
                </div>
                <div className="dev-stat-card">
                    <BarChart3 size={16} />
                    <div>
                        <span>上报完成</span>
                        <strong>{stats.pendingReview}</strong>
                    </div>
                </div>
                <div className="dev-stat-card">
                    <BarChart3 size={16} />
                    <div>
                        <span>已完成</span>
                        <strong>{stats.done}</strong>
                    </div>
                </div>
            </div>

            <div className="dev-view-toggle">
                <button
                    className={viewMode === 'table' ? 'active' : ''}
                    onClick={() => setViewMode('table')}
                >
                    表格视图
                </button>
                <button
                    className={viewMode === 'gantt' ? 'active' : ''}
                    onClick={() => setViewMode('gantt')}
                >
                    甘特视图
                </button>
            </div>

            {viewMode === 'table' ? (
                <div className="dev-table-wrap">
                    <table className="dev-table">
                        <thead>
                            <tr>
                                <th>任务</th>
                                <th>状态</th>
                                <th>优先级</th>
                                <th>负责人</th>
                                <th>审核员</th>
                                <th>截止日期</th>
                                <th>进度</th>
                            </tr>
                        </thead>
                        <tbody>
                            {groupedByType.map((group) => (
                                <React.Fragment key={group.typeKey}>
                                    <tr className="group-row" onClick={() => toggleTypeGroup(group.typeKey)}>
                                        <td colSpan={7}>
                                            <span className="group-toggle">
                                                {collapsedTypeMap[group.typeKey] ? <ChevronRight size={14} /> : <ChevronDown size={14} />}
                                                {group.label}
                                            </span>
                                            <span className="group-count">{group.items.length}</span>
                                        </td>
                                    </tr>
                                    {!collapsedTypeMap[group.typeKey] && group.items.map((task) => {
                                        const p = STATUS_PROGRESS[task.status] ?? 0;
                                        return (
                                            <tr key={task.id}>
                                                <td className="task-title" title={task.title}>{task.title}</td>
                                                <td><span className={`status-tag status-${task.status}`}>{STATUS_LABELS[task.status] || task.status}</span></td>
                                                <td>
                                                    <select
                                                        value={task.priority || 'p2'}
                                                        disabled={assigningTaskId === task.id}
                                                        onChange={(e) => handlePriority(task.id, e.target.value)}
                                                    >
                                                        {PRIORITY_OPTIONS.map((pValue) => (
                                                            <option key={pValue} value={pValue}>{pValue.toUpperCase()}</option>
                                                        ))}
                                                    </select>
                                                </td>
                                                <td>
                                                    <select
                                                        value={task.assignee_user_id || ''}
                                                        disabled={assigningTaskId === task.id}
                                                        onChange={(e) => handleAssign(task.id, e.target.value)}
                                                    >
                                                        <option value="">未分配</option>
                                                        {members.map((m) => (
                                                            <option key={m.id} value={m.id}>
                                                                {m.display_name}{m.is_pm ? ' (PM)' : ''}
                                                            </option>
                                                        ))}
                                                    </select>
                                                </td>
                                                <td>{reviewerName}</td>
                                                <td>
                                                    <input
                                                        type="date"
                                                        value={task.due_at ? new Date(task.due_at).toISOString().slice(0, 10) : ''}
                                                        disabled={assigningTaskId === task.id}
                                                        onChange={(e) => handleDueDate(task.id, e.target.value)}
                                                    />
                                                </td>
                                                <td>
                                                    <div className="row-progress">
                                                        <div style={{ width: `${p}%` }} />
                                                    </div>
                                                </td>
                                            </tr>
                                        );
                                    })}
                                </React.Fragment>
                            ))}
                        </tbody>
                    </table>
                </div>
            ) : (
                <div className="gantt-wrap">
                    <div className="gantt-head">
                        <span>{timeline.start.toLocaleDateString('zh-CN')}</span>
                        <span>{timeline.end.toLocaleDateString('zh-CN')}</span>
                    </div>
                    <div className="gantt-list">
                        {groupedByType.map((group) => (
                            <div key={group.typeKey} className="gantt-group">
                                <div className="gantt-group-head" onClick={() => toggleTypeGroup(group.typeKey)}>
                                    {collapsedTypeMap[group.typeKey] ? <ChevronRight size={14} /> : <ChevronDown size={14} />}
                                    <strong>{group.label}</strong>
                                    <span>{group.items.length}</span>
                                </div>
                                {!collapsedTypeMap[group.typeKey] && group.items.map((task) => {
                                    const progress = STATUS_PROGRESS[task.status] ?? 0;
                                    const due = task.due_at ? new Date(task.due_at) : null;
                                    let widthPct = 8;
                                    if (due) {
                                        const raw = ((due.getTime() - timeline.start.getTime()) / timeline.DAY) / timeline.totalDays;
                                        widthPct = Math.max(8, Math.min(100, Math.round(raw * 100)));
                                    }
                                    return (
                                        <div key={task.id} className="gantt-row">
                                            <div className="gantt-meta">
                                                <strong title={task.title}>{task.title}</strong>
                                                <span>{task.assignee_name || '未分配'} · {STATUS_LABELS[task.status] || task.status}</span>
                                            </div>
                                            <div className="gantt-track">
                                                <div className={`gantt-bar status-${task.status}`} style={{ width: `${widthPct}%` }}>
                                                    <i style={{ width: `${progress}%` }} />
                                                </div>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
}
