import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, BarChart3, Loader2, RefreshCw, Users } from 'lucide-react';
import projectApi from '@/api/project';
import { useAuth } from '@/contexts/AuthContext';
import './DevelopmentProgressPage.css';

const STATUS_ORDER = ['open', 'in_progress', 'pending_review', 'done', 'blocked', 'dismissed'];
const STATUS_LABELS = {
    open: '未开始',
    in_progress: '进行中',
    pending_review: '上报完成',
    done: '已完成',
    blocked: '阻塞',
    dismissed: '已忽略',
};

const DEV_TYPE_LABELS = {
    dev_backend: '后端',
    dev_frontend: '前端',
    dev_ui: 'UI',
    dev_product: '产品',
};

function getDevTypes(row) {
    if (!row) return [];
    return ['dev_backend', 'dev_frontend', 'dev_ui', 'dev_product'].filter((k) => {
        const v = String(row[k] || '').trim();
        return v && v !== '-' && v !== '0';
    });
}

function buildTaskTitle(row, devType) {
    const typeLabel = DEV_TYPE_LABELS[devType] || devType;
    const name = [row.l1_feature, row.l2_feature].filter(Boolean).join(' - ');
    return `[${typeLabel}] ${name || '开发任务'}`;
}

export default function DevelopmentProgressPage() {
    const { id } = useParams();
    const navigate = useNavigate();
    const { user } = useAuth();

    const [project, setProject] = useState(null);
    const [tasks, setTasks] = useState([]);
    const [members, setMembers] = useState([]);
    const [loading, setLoading] = useState(true);
    const [generating, setGenerating] = useState(false);
    const [assigningTaskId, setAssigningTaskId] = useState(null);
    const [error, setError] = useState(null);
    const autoGeneratedRef = useRef(false);

    const autoGenerateTasks = useCallback(async (proj, candidateMembers, featureList) => {
        setGenerating(true);
        try {
            const fallbackAssignee = proj?.pm_user_id || candidateMembers[0]?.id || user?.id;
            const dueAtIso = proj?.due_at ? `${proj.due_at}T18:00:00` : null;
            const generated = [];
            featureList.forEach((row, index) => {
                const types = getDevTypes(row);
                types.forEach((devType) => {
                    generated.push({
                        title: buildTaskTitle(row, devType),
                        description: row.description || '',
                        assignee_user_id: fallbackAssignee,
                        priority: 'p2',
                        due_at: dueAtIso,
                        dev_type: devType,
                        feature_key: `${index}|${devType}`,
                    });
                });
            });
            if (generated.length > 0) {
                await projectApi.generateDevTasks(id, generated);
                const todoRes = await projectApi.getProjectTodos(id);
                setTasks(todoRes.data || []);
            }
        } catch (err) {
            setError(err?.response?.data?.message || err?.message || '自动生成开发任务失败');
        } finally {
            setGenerating(false);
        }
    }, [id, user?.id]);

    const load = useCallback(async () => {
        setLoading(true);
        setError(null);
        try {
            const [projectRes, todoRes, featureRes] = await Promise.all([
                projectApi.getProject(id),
                projectApi.getProjectTodos(id),
                projectApi.getProjectFeatureList(id),
            ]);

            const proj = projectRes.data;
            const todoItems = todoRes.data || [];
            const featureData = featureRes.data || {};
            const featureMembers = featureData.members || [];
            const pm = proj?.pm_user_id
                ? { id: proj.pm_user_id, display_name: proj.pm_name || '项目经理', is_pm: true }
                : null;
            const mergedMembers = pm
                ? [pm, ...featureMembers.filter((m) => m.id !== pm.id)]
                : featureMembers;

            setProject(proj);
            setTasks(todoItems);
            setMembers(mergedMembers);

            if (!autoGeneratedRef.current && todoItems.length === 0 && (featureData.feature_list || []).length > 0) {
                autoGeneratedRef.current = true;
                await autoGenerateTasks(proj, mergedMembers, featureData.feature_list);
            }
        } catch (err) {
            setError(err?.response?.data?.message || err?.message || '加载开发进度失败');
        } finally {
            setLoading(false);
        }
    }, [autoGenerateTasks, id]);

    useEffect(() => {
        if (id) load();
    }, [id, load]);

    const stats = useMemo(() => {
        const total = tasks.length;
        const done = tasks.filter((t) => t.status === 'done').length;
        const inProgress = tasks.filter((t) => t.status === 'in_progress').length;
        const pendingReview = tasks.filter((t) => t.status === 'pending_review').length;
        const progress = total ? Math.round((done / total) * 100) : 0;
        return { total, done, inProgress, pendingReview, progress };
    }, [tasks]);

    const groupedTasks = useMemo(() => {
        const map = {};
        STATUS_ORDER.forEach((k) => { map[k] = []; });
        tasks.forEach((t) => {
            if (!map[t.status]) map[t.status] = [];
            map[t.status].push(t);
        });
        return map;
    }, [tasks]);

    const canAssign = project?.pm_user_id === user?.id;
    const reviewerName = project?.pm_name || '项目经理';

    const handleAssign = async (todoId, assigneeUserId) => {
        if (!assigneeUserId) return;
        try {
            setAssigningTaskId(todoId);
            await projectApi.assignProjectTodo(id, todoId, assigneeUserId);
            const todoRes = await projectApi.getProjectTodos(id);
            setTasks(todoRes.data || []);
        } catch (err) {
            setError(err?.response?.data?.message || err?.message || '分配任务失败');
        } finally {
            setAssigningTaskId(null);
        }
    };

    if (loading) {
        return (
            <div className="page-content">
                <div className="dev-progress-loading"><Loader2 size={20} className="spin" /> 加载中...</div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="page-content">
                <div className="dev-progress-error">{error}</div>
            </div>
        );
    }

    return (
        <div className="page-content dev-progress-page">
            <div className="dev-progress-toolbar">
                <button className="dev-progress-back" onClick={() => navigate(`/project/${id}`)}>
                    <ArrowLeft size={15} /> 返回项目
                </button>
                <button className="dev-progress-refresh" onClick={load}>
                    <RefreshCw size={14} /> 刷新
                </button>
            </div>

            <div className="dev-progress-hero">
                <div>
                    <p className="dev-progress-kicker">Development Progress</p>
                    <h1>{project?.name}</h1>
                    <p className="dev-progress-subtitle">
                        审核员统一为：<strong>{reviewerName}</strong>
                    </p>
                </div>
                <div className="dev-progress-meter">
                    <div className="dev-progress-percent">{stats.progress}%</div>
                    <div className="dev-progress-track">
                        <div className="dev-progress-fill" style={{ width: `${stats.progress}%` }} />
                    </div>
                    <div className="dev-progress-caption">{stats.done}/{stats.total} 已完成</div>
                </div>
            </div>

            {generating && (
                <div className="dev-progress-banner">
                    <Loader2 size={16} className="spin" /> 正在根据功能清单自动生成开发任务...
                </div>
            )}

            <div className="dev-progress-stats">
                <div className="dev-stat-card">
                    <BarChart3 size={16} />
                    <div>
                        <span>总任务</span>
                        <strong>{stats.total}</strong>
                    </div>
                </div>
                <div className="dev-stat-card">
                    <Users size={16} />
                    <div>
                        <span>进行中</span>
                        <strong>{stats.inProgress}</strong>
                    </div>
                </div>
                <div className="dev-stat-card">
                    <BarChart3 size={16} />
                    <div>
                        <span>上报完成</span>
                        <strong>{stats.pendingReview}</strong>
                    </div>
                </div>
                <div className="dev-stat-card">
                    <BarChart3 size={16} />
                    <div>
                        <span>已完成</span>
                        <strong>{stats.done}</strong>
                    </div>
                </div>
            </div>

            <div className="dev-progress-board">
                {STATUS_ORDER.map((status) => (
                    <section key={status} className="dev-board-column">
                        <header>
                            <h3>{STATUS_LABELS[status] || status}</h3>
                            <span>{groupedTasks[status]?.length || 0}</span>
                        </header>
                        <div className="dev-board-list">
                            {(groupedTasks[status] || []).map((task) => (
                                <article key={task.id} className="dev-task-card">
                                    <h4 title={task.title}>{task.title}</h4>
                                    <div className="dev-task-meta">
                                        <span>优先级：{task.priority?.toUpperCase() || '-'}</span>
                                        <span>到期：{task.due_at ? new Date(task.due_at).toLocaleDateString('zh-CN') : '-'}</span>
                                    </div>
                                    <div className="dev-task-row">
                                        <label>负责人</label>
                                        <select
                                            value={task.assignee_user_id || ''}
                                            disabled={!canAssign || assigningTaskId === task.id}
                                            onChange={(e) => handleAssign(task.id, e.target.value)}
                                        >
                                            <option value="">未分配</option>
                                            {members.map((m) => (
                                                <option key={m.id} value={m.id}>
                                                    {m.display_name}{m.is_pm ? ' (PM)' : ''}
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                    <div className="dev-task-row">
                                        <label>审核员</label>
                                        <span>{reviewerName}</span>
                                    </div>
                                </article>
                            ))}
                        </div>
                    </section>
                ))}
            </div>
        </div>
    );
}
